name: Testing Azure CLI

on:
  workflow_dispatch:

jobs:
  test-with-mitmproxy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start mitmproxy
        id: mitmproxy
        uses: yaegashi/mitmproxy-logger-action@main
        with:
          enabled: true
          listen-host: '127.0.0.1'
          listen-port: '8080'
          passphrase: ${{ secrets.MITMPROXY_PASSPHRASE }}

      - name: Azure CLI
        uses: azure/login@v2
        with:
          tenant-id: 3822b9ab-ab2c-4f20-a8cd-abe6ac986c37
          client-id: 4078a16d-f9c0-4215-b4c5-95420f0ed3b2
          subscription-id: 9f2d8ee6-af5b-4947-a34a-8bc5b2445266
          enable-AzPSSession: true

      - name: Run tests with proxy
        run: |
          set -x
          curl -v http://httpbin.org/get
          curl -v https://httpbin.org/get
        env:
          http_proxy: ${{ steps.mitmproxy.outputs.proxy-url }}
          nttps_proxy: ${{ steps.mitmproxy.outputs.proxy-url }}
