name: Example usage of mitmproxy-logger-action

on:
  workflow_dispatch:

jobs:
  test-with-mitmproxy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Start mitmproxy logging
      - name: Start mitmproxy
        id: mitmproxy
        uses: yaegashi/mitmproxy-logger-action@v0.0.5
        with:
          enabled: true
          listen-host: '127.0.0.1'
          listen-port: '8080'
          passphrase: ${{ secrets.MITMPROXY_PASSPHRASE }}
      
      # Configure your application to use the proxy
      - name: Run tests with proxy
        run: |
          set -x
          # Set proxy environment variables
          export HTTP_PROXY=${{ steps.mitmproxy.outputs.proxy-url }}
          export HTTPS_PROXY=${{ steps.mitmproxy.outputs.proxy-url }}
          
          # Example: test HTTP requests
          curl http://httpbin.org/get
          curl -k https://httpbin.org/get
          
          # Your actual test commands would go here
          # npm test
          # python -m pytest
          # etc.
      
      # mitmproxy will automatically stop and upload artifacts when the job completes