name: Testing mitmproxy on Windows

on:
  workflow_dispatch:

jobs:
  test-with-mitmproxy-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start mitmproxy
        id: mitmproxy
        uses: yaegashi/mitmproxy-logger-action@v0.0.15
        with:
          enabled: true
          listen-host: '127.0.0.1'
          listen-port: '8080'
          passphrase: ${{ secrets.MITMPROXY_PASSPHRASE }}

      - name: Run curl command (libcurl)
        shell: cmd
        run: |
          curl -v "http://httpbin.org/get?id=curl"
          curl -v "https://httpbin.org/get?id=curl"
        continue-on-error: true
        env:
          http_proxy: ${{ steps.mitmproxy.outputs.proxy-url }}
          https_proxy: ${{ steps.mitmproxy.outputs.proxy-url }}

      - name: Run certutil command (WinHttp)
        shell: powershell
        run: |
          try {
            netsh winhttp set proxy ${{ steps.mitmproxy.outputs.proxy-url }}
            & bitsadmin /transfer http "http://httpbin.org/get?id=bitsadmin" (Join-Path $env:TEMP http.txt)
            & bitsadmin /transfer https "https://httpbin.org/get?id=bitsadmin" (Join-Path $env:TEMP https.txt)
          } finally {
            netsh winhttp reset proxy
          }
        continue-on-error: true

      - name: Run Windows PowerShell (.NET HttpWebRequest)
        shell: powershell
        run: |
          $proxy = '${{ steps.mitmproxy.outputs.proxy-url }}'
          [System.Net.WebRequest]::DefaultWebProxy = New-Object System.Net.WebProxy($proxy, $true)
          Invoke-WebRequest -Uri "http://httpbin.org/get?id=powershell" -UseBasicParsing
          Invoke-WebRequest -Uri "https://httpbin.org/get?id=powershell" -UseBasicParsing
        continue-on-error: true

      - name: Run PowerShell Core (.NET HttpClient)
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "http://httpbin.org/get?id=pwsh"
          Invoke-WebRequest -Uri "https://httpbin.org/get?id=pwsh"
        continue-on-error: true
        env:
          http_proxy: ${{ steps.mitmproxy.outputs.proxy-url }}
          https_proxy: ${{ steps.mitmproxy.outputs.proxy-url }}
