name: Testing mitmproxy on Windows

on:
  workflow_dispatch:

jobs:
  test-with-mitmproxy-windows:
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Start mitmproxy logging
      - name: Start mitmproxy
        id: mitmproxy
        uses: yaegashi/mitmproxy-logger-action@v0.0.10
        with:
          enabled: true
          listen-host: '127.0.0.1'
          listen-port: '8080'
          passphrase: ${{ secrets.MITMPROXY_PASSPHRASE }}

      - name: Set WinHTTP Proxy
        shell: powershell
        run: netsh winhttp set proxy ${{ steps.mitmproxy.outputs.proxy-url }}

      # Configure your application to use the proxy
      - name: Run tests with proxy
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "http://httpbin.org/get" -UseBasicParsing
          Invoke-WebRequest -Uri "https://httpbin.org/get" -UseBasicParsing
        continue-on-error: true

      - name: Reset WinHTTP Proxy
        shell: powershell
        run: netsh winhttp reset proxy

      # Alternative using curl on Windows (if available)
      - name: Test with curl (if available)
        shell: cmd
        run: |
          curl -v http://httpbin.org/get
          curl -v https://httpbin.org/get
        continue-on-error: true
        env:
          http_proxy: ${{ steps.mitmproxy.outputs.proxy-url }}
          https_proxy: ${{ steps.mitmproxy.outputs.proxy-url }}
      
      # mitmproxy will automatically stop and upload artifacts when the job completes